server:
  port: 8807

spring:
  profiles: two

eureka:
  instance:
    hostname: eureka.server.two
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka.server.one:8806/eureka/,http://eureka.server.three:8808/eureka/